language: python
python:
- '3.6'
install:
- pip install ansible==2.3.0 molecule apache-libcloud
script:
- molecule --debug test
after_script:
- molecule --debug destroy
env:
  global:
  - secure: KXk6YRlHcZEpd+xK7aI4pXtrWd/ONRCZHqNCgL71pNEmoVOzptdNnCsLMktrb6IPSuUHJwEix+ywXcpDOqaUGqNrBIndr8NnkjAQK/Qv+sZGo9/9XP6t80fZVkCHKDAwQHamUvLmsERBrYtC7j/b+xfmc0pUWVyF8nWiMOr+78q4GJU6buJy05ixDBtQKT8u/TmGnyxi0wmjOqKmyEEhaH5BLvPZEQdCBlaQy0LbxlcLJr081+GvY1ughfkgE37JKq8eTul1whUal/9ysWs7bjc7yOy8qIhR5Qj3JmlW1jjilheFESKaTQ276PR9pmFgh65Nuo1n1dDK6dcwd+0vbgcVOIBGlsLN2vLoqpldqLfACp8XA5UchEayWgemEX4UYKYd+sX/vcR8lJVjsM9a2w2nBghUpKPMC3tacNU00SI7dT2BKNTbbW9alMX0CGJa8ugjUz2ObXzxGvLhpwEQ99ziBWeTkBL6BT/e3V7t3BIcSMk/6jHielFgHfANdRXW9cnB3Kbp/StcBZ/vXW2PnAIZbqTKGT2xmh06akZG9LFY9f1OuNno+cAvh8SRyuCH+KDBiOo91zWyZ6/tRJZwl9zSJ7Yn2AGAl9oC2uIYwNOBICQCUDCUE7Mt6rOt4ly9Vp9qiaeTGKbLez/PmHEroFz5CPEu/S86RQv5rCtn90A=
  - secure: l8tCYDKqpHtizFngVdQ2Lb0f4wPH9ZzhtpRIwQtqYak8I7s4oqezwngoaudWyurbD/zLhtY+LFc8/BoC/XZqj55+YC0o03PXhxky2yxxlAYI820U0d94qjb5VcgSMGXV+7vVkH+/FN8rdFUnJVQn7X+j1awzq90jqJrsmyXCRcvL+VtyUdmz3tO1wB5oSyslvhl6SwbYdFoLOlUycSnPEp6UDzEJ1+Qvm6h+64sNp9AkB5s0y6czehytKiCl6667IMsBdmTTjFpnw0NQq/EKNyXmypLD9RWxqXlrh17SHB6goFyogYh/GsA61YlJXyj4n720mNNsOmEaB2X8syBSaSnbn7dEmbYpD/alxeQHpMgKv1MRgfVa2WHrdd9M/Slb95E/b4qM7K+isg4P+xLnof36o6VUTS4qT+IKg4GKjI5Oa+qW3Q8LHpKuTpIXFbo4kmRqeLm0CcU7jk7dOFKVIZxL2frbuTZkGP0G733hKu+DIP7oxJrtZXw4yZslSnvCWZ8WjcYnk1rncddew0pFliDYZdK30ADTspRgh/uHybnbZvIwn7XVdVuQsK7oBHzEjiLSGGRUU15XjFAqOUtHVKu3DuXqhUvYZ9XOml9AKqr3Qk+nBUTzBzqyP8jon2VkMZ2qP44NAiFpJUb/k2RDzFtZBW+7Bwur7pQH3ahGMOg=
  - secure: rSZRaIbCpxzP/cbK24BJ2syFNmLXPn1dfc3Ro+OqjZmZ+Tg5N4Zh0HUuKgTJZG4LQb85NUIW1rWviZOHqX7IskgN/hX+M7+ghyEgZr/KauH9T75Wa2i2C959CQmwLdIPs+DSufWGxe5upZRqHCP5Cw3HWA+9KHcEVdip91rTCShkkFCXXKmOWORCEDbnVJRa8nO/IvBocRBmjeJHJmQwv5Yp3rb9g7DT4tEIpS3RqIYpM0UQCU93SSGbXCTN8PwfTk2jL4JzuVUAdFjljg0E4XZBuL3MGE7DLvZ3sxe7hKbzBRb6iD8dlUitggxHOID/BIsMU9NypT6MVQijUbaSbuDZzMF54lAKgqWBcPl49I8EQ6CdKkABRXAnFdUBZZ2vJSL7HtKCz5MaExpJIGBVNgul0tgHVkOljBMZM6z+CCPZ5mz/FmbEC4Ej3BR+4Kj3FNFVcFuGfbBTax2TOuVEaEP7lG2mHPyDhVNBRVJyh7pzgQpC6z2Mxgfiv7PCnKH1SDCO6XxxpiLnA75nqFQH77zOUOb0/R1dgau87uVOV3ktgHidpGdmPw7pdzGydY/iEQCCLVizg1Z2MvNHkcE3iWDWReyUC5SPr0pOOLrd6B+6SdJT70wOqye4pD/rzebVITpt3IiN3hHtAoWHdFliDbIjvlxSkTWz/6QG0jmcqSo=
before_install:
- openssl aes-256-cbc -K $encrypted_111cffa1dd2d_key -iv $encrypted_111cffa1dd2d_iv
  -in secrets.tar.enc -out secrets.tar -d

notifications:
  slack: nonamed-hq:oNSDgpO1cSanENRp1cXPmINc
