language: python
python:
- '3.6'
install:
- pip install ansible==2.7.9 molecule apache-libcloud
#script:
#- molecule create
#- molecule converge
#- molecule verify
#after_script:
#- molecule destroy
script:
- molecule --debug test
after_script:
- molecule --debug destroy
env:
  global:
  - secure: LMyTu2p4l0uiR6cuQQUmcI9EArao6guTUNuBxGbJW47l53wE0sFt5rP3JNKpmmKeBYJgNzu4Z07al9M/eUD2kJrBNAJuNIC3OtPUPSlkWrGaPe41Npf25BVOFy5Oef4SM4E+cZ9fq7WXpKkuxK8eRACQtHqzRjJVpWBcB3vj5CDloDGIBAZ1WN0rdXL+rJCoEwi2pmKgHpxUnCcw8aA2/+nktx3yfvabLBc5aLZ2OrkNXqzzFwE0Uorlv+QsHJPD+ccFTxnhJrj3Fe1Nor/DrYc4miRs3CtRgrq61GT4wqukDaff/UOA9G9BP5lCxNhfkaidPcWuPMpCJvLIkNX07PyEMHZteBT0fc+5ZDSbbaO0kQbYDx9lV3oue+zyt1F8Tm2HFpRKYP3hIuEtnFYrf2TJas7XiL4vVLNEPGZGOsTi0nspG5ydT89FnfaiFyz2cO8qBXWVTZ6EvwsqUgyORr5fVMwx5Z9tNVMKZPzagS8fmHWKiQfdoFhx2INoJxgXTwuSjLNFmkquUdu3+wjA6B6S6cWkqb9LkWPV7EaQub72SZV3TlIKYYkye9nyde+FEPBZDcoe0DYHTkaw6jcG/TPlaW6gFjidRuSCCZD/ntdfPtsHhBfEb3lUwOE8DMtNh5ZOoaaV0B+MV6i03xLXVi+UmO30/AQj4Ut5wQaqmWk=
  - secure: oemNVZezcCqOBytPhj1pTFJ998ntsbQHYqILjisi1cpWmrsurF/tgpz794OwaucxAUN927LJXjN6kQBlb2WpeLvxHkokeu2ZAEP2d7LtNHq1+iNdZf+KNzakFLtVsapZOdozRZEy3cU/OG9pN7YX0laEas7vJt/3TyTuDR1gobhFvUWCpXcMxmmYOqFK2w/oRdr1ZnHjLixVu1ci1kbky1lDqLFpUDJfLRTWiQC3YJLt1HoKc0lCjyKnf1XUtjvbNVYjS4vVRgwRsnYMFQ8H0m/G7we0M9P5FkrBLHltIWPnbYrvXpfa4t2Y+oGaol4SQkFGWs1pZknkoR+iuv2ZTAXIh5p1/8N0Mlqt9CE4/nAqVdHtl2Cee6eW/EKr7xi2CN4a8to/azJ5Livutndgkd4BerEfWMTNWZlrS9iLpn7vOPk4cYPhueELEJVpkWpe1DiC5XFnF2ANsIr15G4FonD0QB5L0iXGRhhdD22uH5XIjOoPUr1m5s1af1nNz5OftljnX7W4RpTH5jV6s7vAMLVcRsF35yrPaXRqMq1LPDe24HnGjw3PhC8/GKazKKOTYUjMuG7Mrv+b0w3pYh/YL9uewghfAHBSBJ2/ZtULpdpO/De7nibWIE/V4hFgMjuHQdocpTKWsnt8mxlkvZI7l0YnGycLGrz+opipEPNOftQ=
  - secure: QAvpdBy6VQAvzXBc4cPTe4lghw4HpqgulmVyxb8unpmEf25kLeVDh9RmhI5H/Gh6upi66ioPrf8qZBk7pyv4EJJGTvuQ5tnyAdGgFsEV0OBDBU50evRRfQBlCS9TYCyniQCbwBQuHyXhCsD1WGBgWQX/ziyxzjRr4B3juZPyBNVO6qO3X4wSRgAuGkTTs8bIPf5RN4ABaFOPMVuCvySiLP9U2O8TQrtlxqIwGBRjbAzn4pnAdwjwb0+kCQJ1wSNJtRYj32RM8jjuI07ZKBfRdzHPmeSUlJPSiKvwB/n0XNP6e5jqA/jCO0qzo96jp7ZOl/idQzhGVUKyaIsUr26n1ArYTwz2g5qm7oq8/4bUhe9LTDw3xKovnzLUKfYbOZm8nf4dAFeXNpUiNPZgVKwIBwfLBCQNRFmN6vK5cKdkWKLIc9Eg7ziB0T6P1Wn2QpGuQm2vavdf5tfWpuh4S8DbV7L7QEVvWZPqmP6p26+MAeGyj85MnMnkSxnEHIDs0Mdk6QBboDRQCT7vGbZBBzzHwghLxetxAHOaRTUDxmlOPlEZrD/uCC4iEbRVBhotQmI/Zbg+utis7LEWUuD/0jvR5DMEoTA6EzkGtzuzRW+zHfu0xgCC8MSWrYTG4IQVwEajckvgdKUpcFXLEFUhULkfl9d1wXaeiouwhPk/Ab8Qo68=
before_install:
- openssl aes-256-cbc -K $encrypted_111cffa1dd2d_key -iv $encrypted_111cffa1dd2d_iv
  -in secrets.tar.enc -out secrets.tar -d

notifications:
  slack: nonamed-hq:oNSDgpO1cSanENRp1cXPmINc
