language: python
python:
- '3.6'
install:
- pip install ansible==2.5.5 molecule apache-libcloud
script:
- molecule --debug test
after_script:
- molecule --debug destroy
before_install:
- openssl aes-256-cbc -K $encrypted_111cffa1dd2d_key -iv $encrypted_111cffa1dd2d_iv
  -in credentials.tar.gz.enc -out credentials.tar.gz -d

notifications:
  slack: nonamed-hq:oNSDgpO1cSanENRp1cXPmINc
