language: python
python:
- '3.6'
install:
- pip install ansible==2.7.9 molecule apache-libcloud
- pip install pycrypto
script:
- molecule create
- molecule converge
- molecule verify
#- molecule --debug test
after_script:
- molecule destroy
env:
  matrix:
  - GCE_CREDENTIALS_FILE="$(pwd)/hardy-symbol-235210-58b1ba999933.json"
  global:
  - secure: GifNO7Gmoz+9n3/SMPkghrJvAJ9whkie0/qQLh13LvA3F05AB+OGzUw6TAusq8bj6HIoknNhCKujXMkZV99d4qW4hDFgSZMHhgF3ai6IhAO/H9bZPOUMmyUPnLAak/gzfVdvFeQIZqGOUVTmFBa5nH8GqDstzfXX/FL4YTr30iett6yAXw7l7m8pFUNBgqOYNkGMm4yMVfOY5I7XbA7ws3/ezcHxgaEZ8qZnZqRCTY1SZvp25ptoTOfRHOFnM2XEcv0Q3rewEtrcFKsp6wYbF+iSC5d9ugK9Hl81FYtn8sLyR7fc5AeEJd2gzQSGwuQkWd3yQj3yeCfx4E9mwxXi7mWwequWfL+ih/3NbrHUzrSKtcqiulO6PNkYVnTHhi72mLdoW8p4a57VJJFVvm2LnGCjGQNMX0k0dKVcSO5Oay6NraHJJZIsmCX55dmCo5cUBlSntxUkp1P+JIPbET71L6L8i9OdP7zFnhVVoGMczCuBQ++RdWBqldbjMLaGmpP67USG0ePDRrCKhw5ffCAlj1zvGti6InMxcqUTieBVgTrjyY4AoYoDMnmCHu5DavZ//0G8cWYfeSkLVrQlgPqDUUFtPIMck33PYmvtiKjsHm9JKKYFg0lGfDCq2dW41bqiykRV4/W4ohztzmBZk1HGzC+PudHavPvVLJC5bVvaWG4=
  - secure: G30TJrYSxcE2Glqj8PrjamH9WuSphVKT9pyZY/WAw72hFtYOvyScRfRfd68pzU3E53jMI/vJ/TUd0UVYOjBMIfFeHRJ2DxL3ryK6jVXI/xPilI1uPa/djYaRvTVJBt268zlFH03DLV1u0tjXwL3bH193oOQqGFLfOiGZwpg9mgdu3H6Xp7PzQ44NoVZottPFxHjqbaZncEoEIWz8XnpnZgYe6aqeqclruyEVFCNuXhfU9N0qYR8hh4UfXHs5HBR3corU+OConrCZI2Mqld79ESprEHgZmfOIdPgoZG4uYpl4U2hWEMCdcAYOCp9QM24IWCG5okqPgtlVXpA4slMNKGVfPF5MaVpWCF2Xy1gGCLW9de/wkv3HyFmFUyOgSSaWPuWnkXoQTWpt9enHVbQ8py8gT6iR/dsPrgUWSwqXutt0SCgXHKGesHaEN4mZekvnVa40qYyx+KTZA+AD9QNH/lS4K5L3iOM/v3756+0wVJGHVdpmnjh6/ut+uUPWoyKEgJS/3FHzU+nJDWyZxtp1T69sqixgQsGnLGF4Lrjtn0CJAzJhsszTuj/0/Rqxn6rl5uuUQInX0NGlqdYMBo9jGwsQmo0fNCuXdK+LczhLY5EtmOfThjww6l0LiaQwhc1icjKsyuTcB0YzLuiaMWKZWiRDEh1MBu0jAAFAAZy9U6o=
  - secure: dd43NsG5Y9wwTGVC392rH/ezMeDw/SUX7ipVgaSjtjch37qNKKqaYNn3QbSlufgW2otriW3foIrBxLnsCfa3ZZyaG81WO+ReugDKoe6tqG9djcZWCRyGROEKmk25saGCa+wM9fM2jEHAULrOvEl9UVyw1TX9VKFu6Y+vQQCPT/9efJoeaAKtX/AAf2syiTyl99zp22ed4F284B5gz3htkQaILIc6aQzc8iEOt2r3VKXL6WPUQACCMZu/ZRvAkj8VAXfBf9UavM4Y2xZDJ5Orz0fNiU7+7seL3CXzuMWYsK4Wl3A0RefU9/0K9aAWDEEThoup63Zx11Z+xyYORRU94CWfkx//lsmQHvcZew0qDVK1XO/qGRb2+Dnh7GdwKs18+dk6GCG9NCbMDn49mH/I8LVduAcU4kv1NfQTnbiM1ga/YUBfaF6jyRiKkiBoYLaR0mAwCOd9ZqxcKlPxMtjg2p7H2NzdHR1LH7NkjENCNFLDvhJ+d76MF37Jk+zGZaW7NrwljlPHk8Y+SBam0XjJS1a1SlO9uaa8s/8t9dqyy4NSdiAsGhAcNxKL/MeohFH+le+CbLb92B+1PjzdVGVAq/DU7xAb5Bqmx/DlPCMwI9xdl49eQ13Gd7mkEWkLH1NmEb08onyjvfzy/BV9MJjBcn6PeoBVqf8uDWARydVrqag=
before_install:
- openssl aes-256-cbc -K $encrypted_111cffa1dd2d_key -iv $encrypted_111cffa1dd2d_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- mv google_compute_engine /home/travis/.ssh/
- chmod 0600 /home/travis/.ssh/google_compute_engine
notifications:
  slack: nonamed-hq:oNSDgpO1cSanENRp1cXPmINc
