language: python
python:
- '3.6'
install:
- pip install ansible==2.5.5 molecule apache-libcloud
script:
- molecule --debug test
after_script:
- molecule --debug destroy
env:
  global:
  - secure: aWVKoSZkiHfBXUmWEJi9DaJrDIPgz2GmkebAIFh/Xgo2uUjLkO32e9DiHrSnDljosCdSA2u7/U0dUNumKmLCnXJTgFKeRAjbv4ENUOAq9bh4cNPF5aVl2nr+OL8vP3Yi12GT4ldjCoBJsa6RMA7Jv/SezTYUXFsKn2DA/PWYk6+3P/rNjSLdHTCrDk4yOPtz456wQeO0Q0A1bRCssjNQBSxQkfZgIIak9XYI03S5t/czZA1D0D5dWBw60905voyJO4CfQUSGv1onOnuvZmxbM/t2aLFMPulMtvx2F1C4DcN4x+N5bH5mplcfV/yVre3h22PljpoqT03/CyK8vLQrINwC27d4EFjrCpO9uKITRUtXnKSMXde4ZzSNvhB0DWgpGZXb+9p5PwGnflQTpAS2cB9KxAwyYuIlWrIkleQxAsKezyqfPnCjf+WfGFBWcZt5Tc7At9EMqyoRWi90U+zR6+WlMBZ9SLsrjWpVuR2HtbkiCNiFCDXupdhHd/tBjhhcYWvAqnj6TD7h6VJT/nGqaLJ9ix+gCSmePbXzsvVzOMavNC5XEWr2OrbVYFHD9t2a5bjwwzUcTmFjHvbrOOmNjI6JCV5bDva64vjD6dNHNkD2sYHfHX0cucEzLlb70qe9m0wCi+ty/fNv65/Tz9xWLTI+pUFuy855qHwNW0L32q8=
  - secure: dtHvRJzWeL+96fcaLfVi0bUh70vKouD4Nq69elav9oHWegsYH9rQN9+wHwNgC+qjLi3cmXUsu7kpDJSmwaE3uCxwE5Y4YDpnZryqbMr2TdJltPCt7DuBwMSzjIbqBkSAbacFw3FKYFDP3/EKw9M7u5D+Ra8hOs5FlsP1Vy3hcxeQetSRIKPaLeEr+V8fuUlZtAjmCk8g/CNaJqKL1UZfb5JXZ8xvEAHhEiFk5poP7tJ1sbspd7uXdeGEzcGRjDXm0Umn+Um3qzy0/EKd9eJ6geSGF7xafQtjQQkoGC6v4ok/B4jKAIYKpZXbdQH9wN4HwAkfdh88bJ0Ox4S/RRrTNhsFzhMeCPaUBUfxVZdlA2sw1x2IGGAVMsKcf2hnisa7pvcmJv2aYt6hie2fDj3vmjVdyj41ruRboBw4lAhcfdsoD8UOEyHMpmwpBhcil9TJfwdQRySxrHiQRIQHLSBm02eMleCpVXbtHZmpxhGJHkvwXNAm//DmUu2D1tkbY2jRfW9rQVl+giHKpeZejjPvA6uE3vavGMY4cGGrXeQdoL/4x2MYg2j6goXKidTkxVlIRo6p2jdEf6P9Z0e9MhwOGql2pCitDXH2hflNQHTYUIo8BZOWTqhWwRNarKIrc7djW95aiIdKDUg9pLNV1cK/JYixqmzNcR2KgWs0SLUVVms=
  - secure: T5sjilbtPbWCzvmUgJFmh4H3S9fq/ncWHqVcPpR6yNFaLaGyopOuTpW+jHsEQa9doWnDUUG0o66d/f7CM2Sce/t+T3pNabAyNBMkhbDdU8QXdX71t4jZz/mcZj8BZHvP13Ov4TXqJG6F/SeVKfqHm43Rtwan7VpkArFqqYawrbvlds/zcC33X0Q29+nhELaaeZ2T7RFP0hboJjGm5k55VNgeyknC3HaoOmfhxwZ9tivAz7gCiWutVdxMahqaA53rwEPREKOqqypXCRI7shQyi8DEAFJwdQ0w7kwH5oCG0RzYNFDHYJIFOfM6Lm/RRROLLmEK4/1n9W4chPh+TS23Wq2C6ZL3R5xAEdR5f1CNNPsmZdGpwlWANIVPy5/gbCHvHwoOu9j2EPd99irWVdjKRilXtkFPAj1ZoOocBOpZtOW+dbOs+SJizu+Xhe2hldfa0hI6EaWmiGIA1IO4y6QGTVuEdS0RTe1aW9RMWDanglOiRFhuLP432tVXNynF8VCMOcUjqVV9w4siQsaL2s+lkjvKezF7sww/luBRl2grvBV10qFSgf1C8emkAUmLiSdm5AJ7bEj7+JiJHJhrcng0KQazsmJfw4wqYcTNdWiXV6OO7BKf25x72NYAGI5KuSwlMaHiIo0VcuZET9hczr4S+qVfB27TYeyW8t6X1U9LmiI=
before_install:
- openssl aes-256-cbc -K $encrypted_111cffa1dd2d_key -iv $encrypted_111cffa1dd2d_iv
  -in secrets.tar.enc -out secrets.tar -d

notifications:
  slack: nonamed-hq:oNSDgpO1cSanENRp1cXPmINc
