language: python
python:
- '3.6'
install:
- pip install ansible==2.3.0 molecule apache-libcloud
script:
- molecule --debug test
after_script:
- molecule --debug destroy
env:
  global:
  - secure: dyYghkUEPyxwKtgWA/LRwBnxsTsEKrFB0G53OxdOcNOjWp6dxcgKg4eQcqIVZXE06aeK8L8GhssjMnUokaR+vSx6dHantAV3S4NTCnMZ5UzMjM3X+vZUho0gE4tkCy8Yq+uQ/a5vuAu3+YUX+kdyVk8HrgTip9lawQcHu+rY4YdGjKKExt/MiczZV9p8a9O4/gCbK+ALgEcI4pWSgYNnXfjqwqPzhLX1WtKH+jMinLPbiKzZYAYmRxQg3f30O2Fx1gwOQ79TyCiWRlQf1A114+Q7igeaqK1sJFSTdIC8rHw+sE3wF5fl+m/EJEl/QVL7DTb0Yhn9dmqYmg0YTg/KpbO2FU+UWrqaEPN7fUWnd40XpSbRCuoGv3k9qKTAM//wPelW3EvhHOwWPXtRmmC6iuEq+BV7HQHV8a9xcH0B2Ny7OOORDwyEWeyVfm7Lg2CDOzj0fV35SAH0hlzXJxk+9v9ZJnzzkTHIENil6DBszxAtMIRpMrPoLanVZOCO9exCMDmde2rwBw/YsFRTm7wSJEq9OOstzU+iVTa1mbNmahFUqGTRiacYfeKO4j6+Nqj4tJceZdmU1zOxY+O+H9VMdzn6qwktb3hOtx+az8RD47zGzD25wdvb3FOaEkMPtu+79NgL8h260ZRkzzclPGysnr0ZEl3NYIkSshc0jVjOBhA=
  - secure: tseG/43Gx83G8kC1YRJX3yqQ0rPp42IyzCOXMFP9j9U1O2b50uDTZwBhrrIkUTUw+DAkikprr6ec95IDLyR9bXlCVEjFJIM+AG0+lkpP7G0Hwa32y5MM2am3uqz9N8QFQ8DSjmCjEw6dWnOHEkMUMKm+GDTuEYMGK9tThdDxWpAnE/UuYu8h9vgyjCCGz0N4HlwzI3QHQVZsofJFci8ZX1rscXM1p7EXkMEKk1nl5AXnaewGWNSh/X7Q4YZuxepbG9DGzsY4ubEkmLwyYqyUj6jBN6sesaFqk3Y2giOToaGXIhT+e/pwsM73iInA7r8vQiyS2wybEpOI0xKiruRyzNBdnC6u95FDGrUoCr0TJLwfJn7SQ9f1pHI2tHdrGHJgixxkvFP1Rnt1w74ancJBG8sCus21SvHgEoNRmCNmIANIzOOIxvUTyyQoIK6MiMdhNSeEom615tXs2mVTe72OZB9IbQxf4Ge3JYgYXVKnx0kvMiFhB+CtBxfhxHsjGT3KZi1Dptj1UFXWaVyc37l+G8CVtCFgRkR95+51nUhzJsOvh3HC0Kf6suDRORV7ACntViw7vnfv/JLNjPzqFtupU8Q8AEXaQtFgsKIGYJfGtlrw87G9d8TPw7K3emfMP029vLZBHz2qbPToCk8V/Isy4vMXlCUVeu7Ax1gsWEjuKQI=
  - secure: gqOFSHptT/IRUixy2eeGoGCpBLf7WZ/RMkojl7Go6fNae4O1Ya99lAeTj6rexRXfln54YA5rEjzYGUFAmYv6pe7cyvqv1zbB1LZR/hD1SSW/jtcxxUSM/u/ph/701zyvuRnDUSagIW2DELlL+hB9os9yXYANr42r1Iiy7j2/6aWhWZyVm6i7yLksYDeRoRJx+EWe8LvszIg7teLv8mwIyDHeV/uXo/ytSAhcnXUb0d/RFw9TSZjP/yRhz0WvWHE3iXYAtb6U3HOczQ5HRW1piYdp765rizzJE5/hXn+FYqJAwSGVLTJTqscEfnlvj3Tc1HIez5CFwoI4FW8krNPl/W1Gjw9RS9hNltQGujPGavat6uPKrTY5/PYrtv2JHiK4jXaDgBHi+jnBfm5QN60wE+NIuNC4CmvZhUhz5Utjq7KiDgM5QHP48AWw0jM3QUl+i74xwvoFfVgM8ISZh0ahuQSSQ1rp/vQtg8sywSjzrEUux7bm9uDNfTCGDe3Oa42hTLhaiAD+O8r/QN0HYzh15Klk+bHjrPbIN3PJa7wHOl9Zw1JDRumX7HPqdRDiWqnS8F7uvws/udFgYFjwvDsF/skqVEYe+wLOk1qdt+tetgJwJ3YbSZVRR37JF82dUCKE8hEUScR6683eDc+hkCjsI5ty4xZf/zM29t2CB8yl7l0=
before_install:
- openssl aes-256-cbc -K $encrypted_111cffa1dd2d_key -iv $encrypted_111cffa1dd2d_iv
  -in credentials.tar.gz.enc -out credentials.tar.gz -d

notifications:
  slack: nonamed-hq:oNSDgpO1cSanENRp1cXPmINc
