language: python
python:
- '3.6'
install:
- pip install ansible==2.7.9 molecule apache-libcloud
script:
- molecule --debug test
after_script:
- molecule --debug destroy
env:
  global:
  - secure: vbe5ukEJQvElsO/VhNVJgQKQHdosyT+t+sDL+sCGLpE2xH794OaWyYUccxKXFnSnUi3cLZ6JWHuIS1T02Ppa7U124bD2PCaOANQY4FtgYMxVDOL2h6QJ2gwATvm7jlIJ/OmsJEjC4V1qeqBD7taO3ynpOf4wJCXwaRjzW+KDUF4UmK/JAdhjlh/ot+Ql7os3SyJ7zQFqUdeizHqmkrQPkGWIoZkbOJDuvhTMPLgTMK7MiFgxpYDMfgPtHyd7xQKgWkwMypQjzpoq0TfXAItFl/qDlDf/aygKL/h0j9akzIz145CyrKpjF7IMP3yfgfeQvGzxwT1yr3Ti3xXdDAv36LqKuB+da6DHBlhFcBScIRTVzugTAOxBNZUT3UqHo+Jw8XM/SPt2PGn5r0BjR/Ulvr7eEsnOeq77bcCJjHJ8OJM4Enqr7LUM4TM0ka6CqScQUh/1w81+rpQZdojyzf0uAN3nKlfE5usNpFT985WqNy9aV1heeddupxCdcRP/aXVCjmg1/SO3GOmT/uMvoM1OpcjslNT/L3guU3B+oP2z00/oM8Frqz3ZxMnmJUAZEN4s+TUe0gePvSBe9p6Y0nKeIHYkWgtnJ6qDj6CqE6e6xVGFVRFQ7+q05mv3pLn8NhST35fCCz1o1ujmpBzreq4uBAxG2kxtt/H9pBtZ7fC+EjA=
  - secure: QV0eqx3oGWZt9Zm0W7iwXV3P5ZxRHNvoAmU4jytILGwIYbY0Xi62n6DIugAHIHHqnRef4+1L/jA3J/oMOFAiTBpmvPGJko5uXerjrN0IAEkdfWDfJ3CRIf83U4GJpYm0xuQTgp6eIDcMZh5N5hSQa/7ap+sPsn9sh01t0fN8wjcPh0NQ4qFQkzkasAoTmCAKEN6MK99K3b5Zuzyaa9V/ReT/Fu72xkdd1W9/eeWp92iBNhL7LqTGiEUcUdBlkTW7xL5kM6gi7UxEu0pBnEALZATQF/SA1dqhR/Z8a21JP2oOS/biMdUx38KZBj1aMSYPuBnqle44ayBH8lRYnsgpdD/XUbVKRmqaoxvIKfTI5SIUa4WMGQmLLLfBDkMPeF8g0yO88k0FK+SPVwQh+6TD8MlTElYn9siFPEdntXFdNRXNIAq0/RJLNW2LSWwKv+j+9GUvrsSdbGOkWRxE3oyWF+Wlfv8YUwWTXF1kkkWNyjNyBsgCRqtZxK7ReOsO3CHeM1/VpdPDV8Kj3bUvv68OnSCDhLAMXNvCoDJ6zFsyGy9m8ncuGxUXwITAltNWoCJJiVJGguKZ6/pu9HB2h6ePjOAHOi9siZFoYccZb+REzqIsbajzCZ1xHxfH4CGUE+V+LKyRRM4P1TOTvu0yyEfDgnYluOmSVclIwwpiVz3lIz8=
  - secure: lDicARiTrg1kBrU1wnlh3BIhPAlkwuP/se9IoX0E5ckOXaA0TrU4beKuRzU95DqFXA0z3oDCo4rVm1TNrMGGWqnJRSliu4QBoDPRfk1UYQFaZAU5nUUhB2gwgIKElc0nEKaC3sRhLzzBb/NcxO287nRz4S4UMDFyc/V6arcW61Zoex17v3c6sby2Y7yveiXEaEdnjtpRpW9Z0aODcwIUfn+Ui3RI+NsMcw14doDI6M+lKiVB3Wot48quGOKHbtcTsyZyW6wxTMdfelPNrvkyU37W+AMU2x4/ZKTnky7Em2fnoPWCJOyAp59OVQ/JbaXLxe8xiOzgmHYtqbltDI1lcXg0m8PLOsV7HH9E20/630kCXyG4O4UFdfusmgXGJ4pJ/h6rUR2m+UvLxgtAhc/1l9Y0yr1GTWFj9JOHeiiu7k876E1GoboYCOvnCn0hCA/HWb1kBIR1Br8A0cbjMSDV1jLMZfwsadsCCD1TioQomWxNL66UvlvviH92nWdR9gVDAR34iiAW9DO7EfbxepCbI3oU4pbZd6VMNRJHoxffcMIUeSyFIdrm5QF1Lfp2wvicBM1G15dJ6yyY8/hhiSYf7ral39KIBYkbydutL/5cZMuO7Q8rRJMJXI5P1yzl4aqL8bPyfgR+M9x3XtpvidkCNygpxprWRTI2ETOOrALN3gI=
before_install:
- openssl aes-256-cbc -K $encrypted_111cffa1dd2d_key -iv $encrypted_111cffa1dd2d_iv
  -in secrets.tar.enc -out secrets.tar -d

notifications:
  slack: nonamed-hq:oNSDgpO1cSanENRp1cXPmINc
