---
dependency:
  name: galaxy
driver:
  name: gce
lint:
  name: yamllint
platforms:
  - name: reddt-db
    zone: europe-west1-b
    machine_type: g1-small
    image: ubuntu-1604-xenial-v20190306
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
